# Generated by Django 2.1.7 on 2019-03-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
